### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by TheIntelloBox** [PerceiveDev/KillCoinz#1]
Hello,

This is a plugin to, for example, rewards players by money when they kill a mob ?
If yes, when is the release ? :D 

Thanks ! :D

**Comment by foxfirecodes** [comment]
KillCoinz are actually their own unique currency, gotten by killing mobs. I was just doing this as a fun project, I'll let you know though when it's in a releasable state :P

**Comment by TheIntelloBox** [comment]
Oh okay. :)
